Fix/48 Translate the app in french
SAE-S5-01-Developpement-avance/PathPilot-android-client pull request #49
Opened 2024-12-06 13:45 UTC by Mateofsr

2024-12-09 16:59 UTC, Odonata971 requested changes
Great, just minors spelling errors

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="latitude_not_included">La la titude doit être comprise entre -90 et 90</string>
esapce en trop dans la string

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="mandatory_fields">Champs obligatoire</string>
"s" missing to "obligatoire"

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="optional_fields">Champs optionnel</string>
"s" missing to "optionnel"

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="longitude_not_included">La longitude doit être comprise entre -180 et 180</string>
ajoute ° pour les intervalles de latitude /longitude

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="mail_regex_invalided">L\'e-mail doit être écris sous la forme suivante: martin.dupont@path-pilot.fr</string>
doit être "écrit" ou lieu de "écris"

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="informations">tous droits d\'auteur, tous droits de propriété intellectuelle</string>
Majuscule au début de la phrase ?

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="client_contact">Contacte</string>
"Contact" au lieu de "Contacte"

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values/strings.xml
> +    <string name="latitude_not_included">Latitude must be between -90 et 90</string>
forgot "°" after coordinates

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values/strings.xml
>      <string name="already_account"><b>Already have an account ? </b></string>
"information" instead of "informations" line 27 cause information is invariable in english  + line 29 upper case for "write" → "Write"

2024-12-09 16:59 UTC, Odonata971 commented on app/src/main/res/values/strings.xml
> +    <string name="mail_regex_invalided">The email must be written as follows: jhon.doe@path-pilot.en, jhon@mail.com …</string>
no need of "the"

2024-12-09 17:11 UTC, Mateofsr commented
I did all the minors changes.

2024-12-09 17:15 UTC, Odonata971 requested changes

2024-12-09 17:15 UTC, Odonata971 commented on app/src/main/res/values/strings.xml
> +    <string name="latitude_not_included">Latitude must be between -90 et 90</string>
Missing "°" for coordinates

2024-12-09 17:15 UTC, Odonata971 commented on app/src/main/res/values/strings.xml
> +    <string name="longitude_not_included">Longitude must be between -180 and 180</string>
Missing "°" for coordinates

2024-12-09 17:17 UTC, Mateofsr commented
I fix it.

2024-12-10 07:09 UTC, Odonata971 approved these changes
LGTM

2024-12-10 16:05 UTC, merged